import 'package:mevtech/features/course/mock-data/course_category.dart';

class CourseApi {
  Map<String, dynamic> data = {
    'data': [
      {
        'title': 'Executive Diploma in Business Communication',
        'description': '',
        'price': 55000,
        'fileUrl': 'assets/images/ED-Biz-Com.jpg',
        'instructorId': 'Chinedu',
        'id': 'A3B7F9',
        'category': CourseCategory.business,
      },
      {
        'title': 'Executive Diploma in Procurement & Contract Management',
        'description': '',
        'price': 67000,
        'fileUrl': 'assets/images/E-D-Proc-Contract-Mgt.jpg',
        'instructorId': 'Amaka',
        'id': 'X9C2L4',
        'category': CourseCategory.business,
      },
      {
        'title': 'Executive Diploma in Data Analytics',
        'description': '',
        'price': 53000,
        'fileUrl': 'assets/images/E-D- Data Analytics.jpg',
        'instructorId': 'Tunde',
        'id': 'J7K4M1',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Diploma in Business Administration',
        'description': '',
        'price': 30000,
        'fileUrl': 'assets/images/Dip-Business-Admin.jpg',
        'instructorId': 'Ngozi',
        'id': 'V5P9Z3',
        'category': CourseCategory.business,
      },
      {
        'title': 'Diploma in Healthcare Management',
        'description': '',
        'price': 35000,
        'fileUrl': 'assets/images/Dip- Healthcare Mgt.jpg',
        'instructorId': 'Ifeanyi',
        'id': 'R6Q8X0',
        'category': CourseCategory.health,
      },
      {
        'title': 'Mastering Health and Safety Management',
        'description': '',
        'price': 48000,
        'fileUrl': 'assets/images/Mast Health & Safety mgt.jpg',
        'instructorId': 'Funmi',
        'id': 'H2Y5W9',
        'category': CourseCategory.health,
      },
      {
        'title': 'Essentials of Data Visualization using MS Excel',
        'description': '',
        'price': 59000,
        'fileUrl': 'assets/images/Ess-Data-Vis- Ms Excel.jpg',
        'instructorId': 'Olu',
        'id': 'N3B6K7',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Diploma in Construction Management',
        'description': '',
        'price': 31000,
        'fileUrl': 'assets/images/Dip- Construction-Management.jpg',
        'instructorId': 'Amina',
        'id': 'F8T0C4',
        'category': CourseCategory.engineering,
      },
      {
        'title': 'Diploma in Transportation & Logistics Management',
        'description': '',
        'price': 45000,
        'fileUrl': 'assets/images/Dip- Trans & Log mgt.jpg',
        'instructorId': 'Emeka',
        'id': 'W1J9P5',
        'category': CourseCategory.supplyChain,
      },
      {
        'title': 'Diploma in Environment Health and Safety Management',
        'description': '',
        'price': 37000,
        'fileUrl': 'assets/images/Dip- Environ-Health & Safety-Mgt.jpg',
        'instructorId': 'Chika',
        'id': 'L7S4V2',
        'category': CourseCategory.health,
      },
      {
        'title': 'Basics of Data Cleaning',
        'description': '',
        'price': 69000,
        'fileUrl': 'assets/images/Basics-of-Data-Cleaning-card.jpg',
        'instructorId': 'Bayo',
        'id': 'G5R1M8',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Basics of Pandas',
        'description': '',
        'price': 30000,
        'fileUrl': 'assets/images/Basics-of-Pandas-UK.jpg',
        'instructorId': 'Ifunanya',
        'id': 'Y8Q2J7',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Essentials of Data Sourcing & Cleaning',
        'description': '',
        'price': 53000,
        'fileUrl':
            'assets/images/Essentials-of-Data-Sourcing-Cleaning-card.jpg',
        'instructorId': 'Ijeoma',
        'id': 'Z0X6T4',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Data Visualization - Seaborn',
        'description': '',
        'price': 28000,
        'fileUrl': 'assets/images/Data-visualization-seaborn-card.jpg',
        'instructorId': 'Segun',
        'id': 'Q9L3BV',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Data Visualization - Matplotlib',
        'description': '',
        'price': 65000,
        'fileUrl': 'assets/images/Data-Visualization-Matplotlib-card.jpg',
        'instructorId': 'Zainab',
        'id': 'U1PKT8',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Data Visualization - Pandas',
        'description': '',
        'price': 50000,
        'fileUrl': 'assets/images/Data-Visualization-Pandas.jpg',
        'instructorId': 'Kelechi',
        'id': 'P3N8FR',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Diploma in Data Pre-Processing & Exploratory Analysis',
        'description': '',
        'price': 71000,
        'fileUrl':
            'assets/images/Diploma-in-Data-Pre-Processing-and-Exploratory-Analysis-card-1-.jpg',
        'instructorId': 'Nkechi',
        'id': 'D6V2JW',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Mastering Exploratory Data Analysis',
        'description': '',
        'price': 39000,
        'fileUrl':
            'assets/images/Mastering-Exploratory-Data-Analysis-card-1-.jpg',
        'instructorId': 'Sade',
        'id': 'T7R5X0',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Essentials of MS Excel - Formulas and Functions',
        'description': '',
        'price': 53000,
        'fileUrl': 'assets/images/Essential-Ms Excel Form&Func.jpg',
        'instructorId': 'Abiola',
        'id': 'C4K9PS',
        'category': CourseCategory.workplaceTech,
      },
      {
        'title': 'Basics of Microsoft Power BI',
        'description': '',
        'price': 18000,
        'fileUrl': 'assets/images/Basic Microsoft Power-Bi.jpg',
        'instructorId': 'Oluchi',
        'id': 'E8H1YQ',
        'category': CourseCategory.workplaceTech,
      },
      {
        'title': 'Basics of Machine Learning Algorithms',
        'description': '',
        'price': 28000,
        'fileUrl': 'assets/images/Basics of Machine Learn Algo.jpg',
        'instructorId': 'Tope',
        'id': 'J9VWZ4',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Master ChatGPT',
        'description': '',
        'price': 59000,
        'fileUrl': 'assets/images/Master ChatGPT.jpg',
        'instructorId': 'Chioma',
        'id': 'F7RXC2',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Basics of Data Science',
        'description': '',
        'price': 43000,
        'fileUrl': 'assets/images/Basics of Data Science.jpg',
        'instructorId': 'Ibrahim',
        'id': 'R1KLN9',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Diploma in Power BI',
        'description': '',
        'price': 31000,
        'fileUrl': 'assets/images/Diploma in Power BI.jpg',
        'instructorId': 'Adesina',
        'id': 'M5X8JY',
        'category': CourseCategory.workplaceTech,
      },
      {
        'title': 'Diploma in SQL: Beginner to Advanced Levels',
        'description': '',
        'price': 70000,
        'fileUrl': 'assets/images/Diploma-SQL-Begin-to-adv-lev.jpg',
        'instructorId': 'Olufemi',
        'id': 'V3DT8X',
        'category': CourseCategory.softwareDev,
      },
      {
        'title': 'MBA Essentials with Machine Learning',
        'description': '',
        'price': 28000,
        'fileUrl': 'assets/images/MBA Essentials with Machine Learning.jpg',
        'instructorId': 'Ngozi',
        'id': 'Q0N2LW',
        'category': CourseCategory.dataScience,
      },
      {
        'title': 'Basics of Python',
        'description': '',
        'price': 18000,
        'fileUrl': 'assets/images/Basics-of-Python.jpg',
        'instructorId': 'Chukwu',
        'id': 'B8RM5V',
        'category': CourseCategory.softwareDev,
      },
      {
        'title': 'Basics of Digital Marketing',
        'description': '',
        'price': 26000,
        'fileUrl': 'assets/images/Basics of Digital Marketing.jpg',
        'instructorId': 'Ogechi',
        'id': 'X6VPL1',
        'category': CourseCategory.business,
      },
      {
        'title': 'Basics in Human Resource Management',
        'description': '',
        'price': 19000,
        'fileUrl': 'assets/images/Basics-Human-Resource Mgt.jpg',
        'instructorId': 'Micheal',
        'id': '65BJF3',
        'category': CourseCategory.supplyChain,
      },
      {
        'title': 'Basics of Buildings and Construction Works',
        'description': '',
        'price': 34000,
        'fileUrl': 'assets/images/Basics of Build & Const Works.jpg',
        'instructorId': 'Dotun',
        'id': 'HY894D',
        'category': CourseCategory.engineering,
      },
      {
        'title': 'Fundamentals of English Grammar',
        'description': '',
        'price': 22000,
        'fileUrl': 'assets/images/Fundamentals-of-English-Grammar.jpg',
        'instructorId': 'Desire',
        'id': '674GHC',
        'category': CourseCategory.education,
      },
      {
        'title': 'Basics of Accounting',
        'description': '',
        'price': 41000,
        'fileUrl': 'assets/images/Basics of Accounting.jpg',
        'instructorId': 'Biodun',
        'id': 'BY65D1',
        'category': CourseCategory.business,
      },
      {
        'title': 'Basics of Excel Spreadsheet & Workbook',
        'description': '',
        'price': 27000,
        'fileUrl': 'assets/images/Basics of Excel Spreadsheet & Workbook.jpg',
        'instructorId': 'Kunle',
        'id': 'SD56Y2',
        'category': CourseCategory.workplaceTech,
      },
      {
        'title':
            'Executive Diploma in Supply Chain & Logistics in Global Context',
        'description': '',
        'price': 32000,
        'fileUrl':
            'assets/images/Exe Dip Supply Chain & Logistics in Global Context.jpg',
        'instructorId': 'Yayo',
        'id': '980XM4',
        'category': CourseCategory.supplyChain,
      },
    ],
  };

  Future<Map<String, dynamic>> getApiData() async {
    try {
      await Future.delayed(
        const Duration(seconds: 1),
        () {},
      );
      return data;
    } catch (e) {
      return {'error': 'unable to get Data $e'};
    }
  }

  // title
  // description
  // price
  // fileUrl
  // instructorId
  // id
  // category
}
