import 'package:template/features/presentation/widgets/course.dart';

class CourseList {
  final myList = [
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/ED-Biz-Com.jpg',
      title: 'Executive Diploma in Business Communication',
      durationType: 'Flexible Duration',
      duration: '2-3 Weeks Learning',
      category: Course.business,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/E-D-Proc-Contract-Mgt.jpg',
      title: 'Executive Diploma in Procurement & Contract Management',
      durationType: 'Flexible Duration',
      duration: '2-3 Weeks Learning',
      category: Course.business,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/E-D- Data Analytics.jpg',
      title: 'Executive Diploma in Data Analytics',
      durationType: 'Flexible Duration',
      duration: '2-3 Weeks Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Dip-Business-Admin.jpg',
      title: 'Diploma in Business Administration',
      durationType: 'Flexible Duration',
      duration: '1-2 Weeks Learning',
      category: Course.business,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Dip- Healthcare Mgt.jpg',
      title: 'Diploma in Healthcare Management',
      durationType: 'Flexible Duration',
      duration: '1-2 Weeks Learning',
      category: Course.health,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Mast Health & Safety mgt.jpg',
      title: 'Mastering Health and Safety Management',
      durationType: 'Flexible Duration',
      duration: '1 Weeks Learning',
      category: Course.health,
    ),
    const Course(
      id: 'AU',
      imagePath: 'assets/images/Ess-Data-Vis- Ms Excel.jpg',
      title: 'Essentials of Data Visualization using MS Excel',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Dip- Construction-Management.jpg',
      title: 'Diploma in Construction Management',
      durationType: 'Flexible Duration',
      duration: '1-2 Weeks Learning',
      category: Course.engineering,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Dip- Trans & Log mgt.jpg',
      title: 'Diploma in Transportation & Logistics Management',
      durationType: 'Flexible Duration',
      duration: '1-2 Weeks Learning',
      category: Course.supplyChain,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Dip- Environ-Health & Safety-Mgt.jpg',
      title: 'Diploma in Environment Health and Safety Management',
      durationType: 'Flexible Duration',
      duration: '2-3 Weeks Learning',
      category: Course.health,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics-of-Data-Cleaning-card.jpg',
      title: 'Basics of Data Cleaning',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics-of-Pandas-UK.jpg',
      title: 'Basics of Pandas',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'AU',
      imagePath: 'assets/images/Essentials-of-Data-Sourcing-Cleaning-card.jpg',
      title: 'Essentials of Data Sourcing & Cleaning',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'AU',
      imagePath: 'assets/images/Data-visualization-seaborn-card.jpg',
      title: 'Data Visualization - Seaborn',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Data-Visualization-Matplotlib-card.jpg',
      title: 'Data Visualization - Matplotlib',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Data-Visualization-Pandas.jpg',
      title: 'Data Visualization - Pandas',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'MEV',
      imagePath:
          'assets/images/Diploma-in-Data-Pre-Processing-and-Exploratory-Analysis-card-1-.jpg',
      title: 'Diploma in Data Pre-Processing & Exploratory Analysis',
      durationType: 'Flexible Duration',
      duration: '1-2 Weeks Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'AU',
      imagePath:
          'assets/images/Mastering-Exploratory-Data-Analysis-card-1-.jpg',
      title: 'Mastering Exploratory Data Analysis',
      durationType: 'Flexible Duration',
      duration: '1 WeekLearning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Essential-Ms Excel Form&Func.jpg',
      title: 'Essentials of MS Excel - Formulas and Functions',
      durationType: 'Flexible Duration',
      duration: '6-9 Hours Learning',
      category: Course.workplaceTech,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basic Microsoft Power-Bi.jpg',
      title: 'Basics of Microsoft Power BI',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.workplaceTech,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Machine Learn Algo.jpg',
      title: 'Basics of Machine Learning Algorithms',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Master ChatGPT.jpg',
      title: 'Master ChatGPT',
      durationType: 'Flexible Duration',
      duration: '1 week Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Data Science.jpg',
      title: 'Basics of Data Science',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Diploma in Power BI.jpg',
      title: 'Diploma in Power BI',
      durationType: 'Flexible Duration',
      duration: '1-2 weeks Learning',
      category: Course.workplaceTech,
    ),
    const Course(
      id: 'MEV',
      imagePath: 'assets/images/Diploma-SQL-Begin-to-adv-lev.jpg',
      title: 'Diploma in SQL: Beginner to Advanced Levels',
      durationType: 'Flexible Duration',
      duration: '1-2 weeks Learning',
      category: Course.softwareDev,
    ),
    const Course(
      id: 'AU',
      imagePath: 'assets/images/MBA Essentials with Machine Learning.jpg',
      title: 'MBA Essentials with Machine Learning',
      durationType: 'Flexible Duration',
      duration: '4-5 weeks Learning',
      category: Course.dataScience,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics-of-Python.jpg',
      title: 'Basics of Python',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.softwareDev,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Digital Marketing.jpg',
      title: 'Basics of Digital Marketing',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.business,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics-Human-Resource Mgt.jpg',
      title: 'Basics in Human Resource Management',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.supplyChain,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Build & Const Works.jpg',
      title: 'Basics of Buildings and Construction Works',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.engineering,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Fundamentals-of-English-Grammar.jpg',
      title: 'Fundamentals of English Grammar',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.education,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Accounting.jpg',
      title: 'Basics of Accounting',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.business,
    ),
    const Course(
      id: 'CIQ',
      imagePath: 'assets/images/Basics of Excel Spreadsheet & Workbook.jpg',
      title: 'Basics of Excel Spreadsheet & Workbook',
      durationType: 'Flexible Duration',
      duration: '4-6 Hours Learning',
      category: Course.workplaceTech,
    ),
    const Course(
      id: 'MEV',
      imagePath:
          'assets/images/Exe Dip Supply Chain & Logistics in Global Context.jpg',
      title: 'Executive Diploma in Supply Chain & Logistics in Global Context',
      durationType: 'Flexible Duration',
      duration: '2-3 Weeks Learning',
      category: Course.supplyChain,
    ),
  ];
}
